services:
  # 3proxy Manager Web Service
  auth-proxy:
    build: .
    container_name: auth-proxy-manager
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - proxy-network

  3proxy:
    image: 3proxy/3proxy:latest
    container_name: 3proxy-auth
    volumes:
      - ./config:/usr/local/3proxy/conf
    ports:
      - 4128:1080
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge

volumes:
  config:
  logs:
